In [1]:
import numpy as np
from numpy import linalg as LA
import numpy as np
from scipy import integrate
from matplotlib.pylab import *
%matplotlib inline

Define the matrix A:

In [22]:
A = np.array([[0., 1], [-6, -5]])
print A

[[ 0.  1.]
 [-6. -5.]]


Calculate Eigenvalues and Eigenvectors:

In [16]:
w, v =  LA.eig(A)

Display the EigenValues:

In [17]:
print w

[-2. -3.]


Display the EigenVectors:

In [21]:
for i in xrange(len(w)):
    print v[:,i]

[ 0.4472136  -0.89442719]
[-0.31622777  0.9486833 ]


In [26]:
T = np.array([[1, 1],[-3, -2]])
print T

[[ 1  1]
 [-3 -2]]


In [27]:
print LA.inv(T)

[[-2. -1.]
 [ 3.  1.]]


In [28]:
B = np.array([[0, 1, 0],[0, 0, 1],[4, 4, -1]])
print B

[[ 0  1  0]
 [ 0  0  1]
 [ 4  4 -1]]


In [30]:
w_2, v_2 =  LA.eig(B)
print w_2

[-2. -1.  2.]


In [3]:
C = np.array([[0, 1, 0, 0],[-2, 0, 1, 0], [0, 0, 0, 1], [1, 0, -1, 0]])
print C

[[ 0  1  0  0]
 [-2  0  1  0]
 [ 0  0  0  1]
 [ 1  0 -1  0]]


In [4]:
w_3, v_3 =  LA.eig(C)
print w_3

[ 0.+1.61803399j  0.-1.61803399j  0.+0.61803399j  0.-0.61803399j]
